export const wordList = [
    // Basic filler words
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
    "for", "not", "on", "with", "he", "as", "you", "do", "at", "this",
    "but", "his", "by", "from", "they", "we", "say", "her", "she", "or",
    "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    "when", "make", "can", "like", "time", "no", "just", "him", "know",
    "take", "people", "into", "year", "your", "good", "some", "could",
    "them", "see", "other", "than", "then", "now", "look", "only", "come",
    "its", "over", "think", "also", "back", "after", "use", "two", "how",
    // Sherlock / Mystery Theme (converted to lowercase)
    "sherlock", "holmes", "watson", "moriarty", "detective", "mystery", "clue",
    "logic", "reason", "deduction", "crime", "murder", "victim", "suspect",
    "alibi", "evidence", "witness", "poison", "arsenic", "cyanide", "pistol",
    "revolver", "bullet", "wound", "blood", "knife", "blade", "dagger",
    "rope", "garrote", "river", "thames", "fog",
    "mist", "shadow", "dark", "night", "gaslight", "cobblestone", "carriage",
    "hansom", "cab", "driver", "horse", "whip", "coat", "hat", "pipe",
    "smoke", "tobacco", "ash", "magnifying", "glass", "violin", "chemistry",
    "lab", "experiment", "solution", "case", "client", "report", "telegram",
    "letter", "note", "cipher", "secret", "hidden", "treasure", "jewel", "diamond",
    "ruby", "pearl", "necklace", "ring", "theft", "robbery", "burglary", "blackmail",
    "scandal", "irene", "adler", "mycroft", "lestrade", "gregson", "hopkins",
    "scotland", "yard", "police", "constable", "inspector", "agent", "spy",
    "traitor", "foreign", "office", "government", "queen", "king", "royal",
    "palace", "crown", "sign", "four", "study", "scarlet", "valley", "fear",
    "hound", "baskerville", "moor", "grimpen", "mire", "butterfly", "net",
    "spear", "harpoon", "pig", "black", "peter", "speckled", "band", "snake",
    "swamp", "adder", "red", "headed", "league", "tunnel", "bank", "vault",
    "gold", "coin", "money", "greed", "envy", "anger", "revenge", "hate",
    "love", "jealousy", "madness", "insanity", "asylum", "doctor", "surgeon",
    "army", "afghanistan", "shoulder", "leg", "cane", "limp", "invalid", "nurse",
    "housekeeper", "mrs", "hudson", "baker", "street", "door", "bell", "knock",
    "visitor", "stranger", "enemy", "friend", "reichenbach", "falls", "final",
    "problem", "empty", "house", "professor", "diogenes", "club", "greek",
    "interpreter", "naval", "treaty", "bruce", "partington", "plans", "subway",
    "train", "station", "victoria", "waterloo", "charing", "cross", "pall", "mall",
    "strand", "fleet", "newspaper", "article", "headline", "ad", "agony",
    "column", "code", "message", "signal", "lantern", "whistle", "dog", "bark",
    "howl", "footprint", "mud", "clay", "dust", "carpet", "curtain", "window",
    "shard", "broken", "lock", "pick", "skeleton", "key", "safe",
    "dial", "turn", "click", "open", "shut", "trap"
];

