export const wordList = [
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
    "for", "not", "on", "with", "he", "as", "you", "do", "at", "this",
    "but", "his", "by", "from", "they", "we", "say", "her", "she", "or",
    "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    "when", "make", "can", "like", "time", "no", "just", "him", "know",
    "take", "people", "into", "year", "your", "good", "some", "could",
    "them", "see", "other", "than", "then", "now", "look", "only", "come",
    "its", "over", "think", "also", "back", "after", "use", "two", "how",
    "our", "work", "first", "well", "way", "even", "new", "want", "because",
    "any", "these", "give", "day", "most", "us", "is", "are", "was", "were",
    "been", "has", "had", "did", "does", "going", "went", "gone", "am", "im",
    "system", "program", "code", "data", "link", "web", "site", "page",
    "click", "type", "key", "mouse", "screen", "monitor", "pixel", "byte",
    "bit", "bug", "fix", "run", "loop", "if", "else", "for", "while",
    "var", "let", "const", "function", "class", "object", "array", "string",
    "number", "boolean", "null", "undefined", "true", "false", "return",
    "import", "export", "default", "from", "async", "await", "promise",
    "error", "try", "catch", "throw", "new", "this", "super", "extends",
    "void", "any", "never", "unknown", "symbol", "bigint", "map", "set",
    "list", "queue", "stack", "tree", "graph", "node", "edge", "vertex",
    "root", "leaf", "child", "parent", "sibling", "ancestor", "descendant",
    "search", "sort", "filter", "reduce", "map", "forEach", "find", "some",
    "every", "includes", "indexOf", "join", "split", "slice", "splice",
    "push", "pop", "shift", "unshift", "concat", "reverse", "sort", "fill",
    "copyWithin", "entries", "keys", "values", "from", "of", "isArray"
];
